### ISSUE TITLE
Crushed Silver Ores were not able to be milling as other ores properly 

### ISSUE THREAD

**Issue by aestilog** [DM-Earth/Cabricality#100]
粉碎铁矿石可以通过石墨变成三个铁粉，然而粉碎银矿石不能被加工

**Comment by KrLite** [comment]
That's the game design. Silver ores are just banned because we don't want players to craft silver coins in that way. Trading yields silver coins instead.

游戏的刻意设计便如此。玩家们不应该通过挖矿获得银币，而是需要通过交易获取银制品。
