### ISSUE TITLE
[Bug] Lead (and a few other) Ingots cannot be created through a smeltery

### ISSUE THREAD

**Issue by NyakoFox** [DM-Earth/Cabricality#101]
The recipes are just missing and don't work, making molten lead useless.

Additionally, Crushed Lead Ore is hidden from REI, and we can't figure out if that's intentional or not.

No idea if this is related to that or not:

https://user-images.githubusercontent.com/87289390/214452983-3dbddc3a-af98-4c39-8ef0-ca729331dd81.mp4

**Comment by JieningYu** [comment]
Based

**Comment by KrLite** [comment]
> Based

Absolutely

**Comment by NyakoFox** [comment]
why based :(

**Comment by NyakoFox** [comment]
looks like this happens to tin as well, and you can't even make plates using a mechanical press (the only recipe that appears is for a compressor, and you can't make those...)

**Comment by KrLite** [comment]
Weird. I thought I solved this in beta 6 but seems not. Maybe something just messed up during the recipe registration.

**Comment by JieningYu** [comment]
> looks like this happens to tin as well, and you can't even make plates using a mechanical press (the only recipe that appears is for a compressor, and you can't make those...)

Plates pressing has been fixed in dev

**Comment by JieningYu** [comment]
fixed with cftags.

**Comment by NyakoFox** [comment]
> Additionally, Crushed Lead Ore is hidden from REI, and we can't figure out if that's intentional or not.

Still curious about this by the way -- seems like a few crushed ores are missing from REI.

**Comment by JieningYu** [comment]
Create did it.

**Comment by JieningYu** [comment]
> > Additionally, Crushed Lead Ore is hidden from REI, and we can't figure out if that's intentional or not.
> 
> Still curious about this by the way -- seems like a few crushed ores are missing from REI.

Fixed this in dev
