### ISSUE TITLE
Piglins ignore gold armor on player

### ISSUE THREAD

**Issue by NoMoreStars** [DM-Earth/Cabricality#112]
Piglins will attack players even when wearing vanilla gold armor. Tested out with Hephaestus Forge's Gold modifier as well for it's armor sets and get the same results, Piglins ignore the armor and attack the player unprovoked.

**Comment by birdwing** [comment]
I had this same iss @NoMoreStars 
I found that if you are wearing more than 1 peace of Hephaestus armour, then **all** of the pieces must have the "Golden" modifier.

If 1 piece has golden and another doesn't, they attack.

**Comment by KrLite** [comment]
Reopened with issue template here: #147 
This issue will be closed soon.
