### ISSUE TITLE
Steel tools/armors are strange

### ISSUE THREAD

**Issue by JieningYu** [DM-Earth/Cabricality#12]

**Comment by KrLite** [comment]
agree.

**Comment by JieningYu** [comment]
非常坏属性，恨来自瓷器，英雄联盟

**Comment by KrLite** [comment]
Fixed.

_Plus, I think steel tools are associated with fire resistant._

<img width="394" alt="image" src="https://user-images.githubusercontent.com/68179735/188631393-21ab675d-3641-4992-9d91-015e195dd96b.png">

**Comment by JieningYu** [comment]
opog
