### ISSUE TITLE
更改酷热构件配方实现方法以暂时解决REI显示问题

### ISSUE THREAD

**Issue by TexBlock** [DM-Earth/Cabricality#122]
REI无法显示可能是因为步骤太多了（？

不知道改成这样可不可以：

1. 注液 `167mB / 13500dP` 的 液态灵魂， 注液 `1000mB / 81000dP` 的 熔岩 -> 酷热构件（1/3）
2. 注液 `167mB / 13500dP` 的 液态灵魂， 注液 `1000mB / 81000dP` 的 熔岩 -> 酷热构件（2/3）
3. 注液 `167mB / 13500dP` 的 液态灵魂， 注液 `1000mB / 81000dP` 的 熔岩 -> 酷热构件

**Comment by JieningYu** [comment]
目前仅2步骤，当只有1步骤才能正常显示

**Comment by EvanHsieh0415** [comment]
經測試 只要是連續兩個filling就會顯示錯誤
