### ISSUE TITLE
Frame rate drops from 60fps to 12fps while crafting and dragged items desync from system mouse cursor

### ISSUE THREAD

**Issue by WarpZone32** [DM-Earth/Cabricality#133]
I suspect that this lag is caused by whichever mod blurs the entire screen while the crafting menu is open. 

I can't find any options to disable this blur, but it doesn't happen in Vanilla 1.18.2.

(Unrelated, but pressing the Config button on the mods menu causes a crash, so I can't find the option myself unless I read through every single config file, or disable the mods one by one and start a new world, etc.)

**Comment by WarpZone32** [comment]
Heh. Found it.

backgroundBlur = false in Cabricality.toml

I suppose that explains why google search wasn't helpful. It kept pointing to a mod called Blur. And only Blur. (Because, really, who would make a mod that duplicates the functionality of Blur in a world where we already have Blur?)

This should probably be set to false by default. Game is literally unplayable if I can't smear a stack of planks around in a vague square to quickly craft a chest.

FWIW: NVIDIA GeForce MX330, driver version 30.0.15.1259

Good luck. :)

**Comment by JieningYu** [comment]
@KrLite

**Comment by JieningYu** [comment]
actually just press `=` key to open cabf config
