### ISSUE TITLE
add heracles + open parties and claims

### ISSUE THREAD

**Issue by OrdinaryCloverOC** [DM-Earth/Cabricality#140]
these are modrinth alternatives to ftb mods. heracles will definitely be more time consuming to implement tho. open parties and claims supports create.

**Comment by OrdinaryCloverOC** [comment]
*heracles isn't on 1.18.2 sorry, keeping for open parties and claims

**Comment by KrLite** [comment]
Reopened with issue template here: #143 
This issue will be closed soon.
