### ISSUE TITLE
Insane Frame Drop whenever opening a quest

### ISSUE THREAD

**Issue by ThxnderXD** [DM-Earth/Cabricality#141]
thinking its something to do with the purple box animation thing but im not sure
idk if theres a way to disable the animation or something but if there is please tell me how i have no clue
<img width="1920" alt="image" src="https://github.com/DM-Earth/Cabricality/assets/61764591/74f76da6-1399-466f-92d2-980da431e91e">

**Comment by JieningYu** [comment]
should be fixed in 0.3

**Comment by KrLite** [comment]
> should be fixed in 0.3

Yep. It's gonna be sooooon
