### ISSUE TITLE
[BUG]: Crash on Malum Fire Rite

### ISSUE THREAD

**Issue by KrLite** [DM-Earth/Cabricality#144]
### What Happened?

**From [KaosDragon:](https://github.com/KaosDragon)** Trying to use the smelting fire rite (eldritch, arcane, infernal, infernal on a runewood totem) causes a crash when it attempts to smelt.

### Steps to Reproduce

As title says.

### Cabricality Version

0.2.4

**Comment by KrLite** [comment]
Could you please provide detailed information about steps to reproduce?

**Comment by KaosDragon** [comment]
Step 1: Build the totem. https://i.gyazo.com/eed4895970ce64c6d9e0e43b9c81a658.png

Step 2: Activate it.

Step 3: Crash.

**Comment by KrLite** [comment]
It true crashes. According to the log it is a index out of bounds issue produced by class `ca.rttv.malum.util.helper.DataHelper`. A fast mixin may fix that.

**Comment by KrLite** [comment]
![2023-07-18_01 34 18](https://github.com/DM-Earth/Cabricality/assets/68179735/a3082eda-7f89-450d-bc30-04f5ad067442)

### Fixed. As the index out of bounds, just make the bounds larger.

<img width="823" alt="image" src="https://github.com/DM-Earth/Cabricality/assets/68179735/1c4a82fc-7d25-4271-940a-e9e4591af132">
