### ISSUE TITLE
Server-side Cabricality

### ISSUE THREAD

**Issue by a16239438** [DM-Earth/Cabricality#15]
在下载内容后我将其中的config，kubejs与mod文件夹扔到1.18版本的fabric服务端，运行后服务端立刻报错 显示 Incompatible mod set!

**Comment by JieningYu** [comment]
以后会做，现在可以拿局域网联机（可以配置在线模式）。
另：建议拿英语作为issue标题

**Comment by JieningYu** [comment]
https://github.com/DM-Earth/Cabricality-server
