### ISSUE TITLE
[BUG]: Could not initialize class com.mojang.blaze3d.systems.RenderSystem

### ISSUE THREAD

**Issue by Quezler** [DM-Earth/Cabricality#152]
### What Happened?

When i try to open the pack from within the apple m1 modrinth client i get this:

![Screenshot 2023-08-08 at 14 13 23](https://github.com/DM-Earth/Cabricality/assets/3179271/31856789-1706-431a-8c81-6fc2d39de704)
[crash-2023-08-08_14.12.20.4401-quilt_loader.txt](https://github.com/DM-Earth/Cabricality/files/12290965/crash-2023-08-08_14.12.20.4401-quilt_loader.txt)

### What Should Happen?

I expected the game to launch

### Steps to Reproduce

![Screenshot 2023-08-08 at 14 14 51](https://github.com/DM-Earth/Cabricality/assets/3179271/bbafc10a-78ff-4c07-a416-825128cbe39a)

### Cabricality Version Check

Yes, I'm playing with Cabricality 0.3

### Crash Log

see file attached in the what happened section

### Anything Else?

the pack description sounds appealing, looking forward to being able to play it someday 🙂

**Comment by JieningYu** [comment]
Could you please provide a full client log (from boot up to crash)?

**Comment by KrLite** [comment]
That's weird

**Comment by JieningYu** [comment]
That's weird

**Comment by Quezler** [comment]
> Could you please provide a full client log (from boot up to crash)?

Oh yes of course, didn't realize it wasn't part of the log provided by the popup:

[latest.log](https://github.com/DM-Earth/Cabricality/files/12302273/latest.log)

**Comment by JieningYu** [comment]
This might be an issue of theseus as the lwjgl native lib can't be found.
