### ISSUE TITLE
[BUG]: Mods can't download with Prism Launcher.

### ISSUE THREAD

**Issue by f24816** [DM-Earth/Cabricality#153]
### What Happened?

Works with the Modrinth launcher but not with Prism.

### Steps to Reproduce

Download the modpack using Prism Launcher.

### Cabricality Version Check

Yes, I'm playing with Cabricality 0.3

**Comment by JieningYu** [comment]
This might be your network issue. Prismlauncher's mod downloading function is working as intended at my side.
