### ISSUE TITLE
[MOD]: Modern Dynamics

### ISSUE THREAD

**Issue by TexBlock** [DM-Earth/Cabricality#155]
### Mod Link

https://modrinth.com/mod/modern-dynamics

### Propose Reason?

Modern Dynamics has a better user experience than Industrial Revolution's pipes, for example MD has redstone controls and better placement than indrev.

**Comment by JieningYu** [comment]
🥰

**Comment by KrLite** [comment]
<img width="61" alt="image" src="https://github.com/DM-Earth/Cabricality/assets/68179735/95b23705-2776-4b62-933e-b0483b54ac95">

**Comment by JieningYu** [comment]
🥵

**Comment by Gebardensprache** [comment]
I think we can add it in now

**Comment by JieningYu** [comment]
yep
