### ISSUE TITLE
[1.0]: Mods Migration

### ISSUE THREAD

**Issue by KrLite** [DM-Earth/Cabricality#157]
### Currently Blocking

- [x] **Implemented**
  - [X] [Light Emitting Diode](https://modrinth.com/mod/led) | [`Port` Light Emitting Triode](https://github.com/KessokuTeaTime/Light-Emitting-Triode)
           `Replaced:` `Port` Light Emitting Triode
  - [X] [Interference API](https://modrinth.com/mod/interference)
           `Deprecated:` A dependency of `Deprecated` Light Emitting Diode
  - [X] ~[Catwalks Inc.](https://www.curseforge.com/minecraft/mc-mods/catwalks-inc)~
         `Deprecated:` Useless
  - [x] [Malum (Quilt)](https://www.curseforge.com/minecraft/mc-mods/malum-quilt)
        `Deprecated:` Insignificance
        `In Progress`
- [X] **Other**
  - [X] [CTM Refabricated](https://modrinth.com/mod/ctm-refabricated) | [`Replacement` Athena](https://modrinth.com/mod/athena-ctm)
        `Replaced:` `Replacement` Athena
  - [X] [Modern Dynamics](https://modrinth.com/mod/modern-dynamics)
- [X] **Core Mod**

**Comment by JieningYu** [comment]
why just rename the 1192 one

**Comment by KrLite** [comment]
> why just rename the 1192 one

Because I have a reason: the reason is, there's a reason which I'm having, related to this topic. However, instead of telling you the fact, I'll just tell you the reason why I'm having the reason, to do that.

**Comment by JieningYu** [comment]
> > why just rename the 1192 one
> 
> Because I have a reason: the reason is, there's a reason which I'm having, related to this topic. However, instead of telling you the fact, I'll just tell you the reason why I'm having the reason, to do that.

so what's the answer of the reason pointed by your reason

**Comment by Gebardensprache** [comment]
Are you guys talking in tongue twisters?

**Comment by Gebardensprache** [comment]
SO Is this issue need Assignees?

**Comment by TexBlock** [comment]
I'd like to say that I think we should go with 1.19.2 first, because currently some mods are still in beta in 1.20.1, which will increase the instability of the modpacks. 
Currently there is only one version of Create Fabric out at 1.20.1, which I think still leaves some uncertainty.

**Comment by Gebardensprache** [comment]
> I'd like to say that I think we should go with 1.19.2 first, because currently some mods are still in beta in 1.20.1, which will increase the instability of the modpacks.
> Currently there is only one version of Create Fabric out at 1.20.1, which I think still leaves some uncertainty.

要追就追Latest，MODERN

**Comment by JieningYu** [comment]
MODERN批

**Comment by TexBlock** [comment]
> > I'd like to say that I think we should go with 1.19.2 first, because currently some mods are still in beta in 1.20.1, which will increase the instability of the modpacks.
> > Currently there is only one version of Create Fabric out at 1.20.1, which I think still leaves some uncertainty.
> 
> 要追就追Latest，MODERN

OK, LATEST MAN (

**Comment by KrLite** [comment]
This is a long-term run so we have plenty of time preparing our mods. Also, Cabricality 1.20.1 won't simply be a copy of which is in 1.18.2, but a new modpack while preserving the original bloodline.

**Comment by JieningYu** [comment]
WoW

**Comment by Gebardensprache** [comment]
Malum reborn so close
