### ISSUE TITLE
[1.0]: Create Fabric DM-Earth Edition

### ISSUE THREAD

**Issue by TexBlock** [DM-Earth/Cabricality#165]
### [Create Fabric DM-Earth Edition](https://github.com/DM-Earth/create-fabric-dme-edition) TODO:
- [ ] Fix recipe displays on **REI** (Temporarily implemented by [CreateFabricREIBugFix DM-Earth Edition](https://github.com/DM-Earth/create-fabric-rei-fix-dme-edition))
- [x] Compatibility with **Hephaestus**
- [X] Compatibility with **Sodium** `0.5+`
- [x] ~Upload to Modrinth?~ Upload to Modrinth and CurseForge as not listed

### [Flywheel Fabric DM-Earth Edition](https://github.com/DM-Earth/flywheel-fabric-dme-edition) TODO:
- [X] Compatibility with **Sodium** `0.5+`

**Comment by AlphaMode** [comment]
Noice

**Comment by JieningYu** [comment]
wow it's alphamode

**Comment by TexBlock** [comment]
wow it's alphamode

**Comment by KrLite** [comment]
wow it's alphamode

**Comment by AlphaMode** [comment]
wow it's alphamode

**Comment by RawDiamondMC** [comment]
wow it's alphamode

**Comment by TexBlock** [comment]
crappy curseforge
![image](https://github.com/DM-Earth/Cabricality/assets/65154269/4feeda93-0ea6-42ae-84ec-74cc957ee61a)

**Comment by KrLite** [comment]
> crappy curseforge ![image](https://user-images.githubusercontent.com/65154269/273153489-4feeda93-0ea6-42ae-84ec-74cc957ee61a.png)

crapseforge

**Comment by TexBlock** [comment]
official create-fabric fixed

**Comment by RawDiamondMC** [comment]
Why close this issue so late?

**Comment by TexBlock** [comment]
> Why close this issue so late?

Because I'm caught up in life.

**Comment by TexBlock** [comment]
@KrLite Please archive these three repos. I don't have permission to archive them.

**Comment by JieningYu** [comment]
archived

**Comment by TexBlock** [comment]
> archived

this -> https://github.com/DM-Earth/CreateFabricREIBugFixDMEEdition

**Comment by JieningYu** [comment]
archived

**Comment by RawDiamondMC** [comment]
> archived

archiver

**Comment by JieningYu** [comment]
Archive Utilities

**Comment by KrLite** [comment]
The Unarchiver

**Comment by JieningYu** [comment]
Keka
