### ISSUE TITLE
[BUG]: It is much more longer to craft a matrix than CAB

### ISSUE THREAD

**Issue by reslRESL** [DM-Earth/Cabricality#170]
### What Happened?

![time_cabf](https://github.com/DM-Earth/Cabricality/assets/126566700/8a9d30ec-ae8e-46b0-9960-d44b6f2bbc55)

### What Should Happen?

Change each ratio to fix it.

### Steps to Reproduce

Just use REI.

### Cabricality Version Check

Yes, I'm playing with Cabricality 0.3.1

**Comment by JieningYu** [comment]
intended. it this too much?

**Comment by reslRESL** [comment]
Absolutely yes.
