### ISSUE TITLE
[BUG]: Incompatible with mod essential?

### ISSUE THREAD

**Issue by CausalKarma26** [DM-Earth/Cabricality#178]
### What Happened?

I have been trying for weeks to make this modpack work with the mod "essential": I've tried one mod at a time, changing versions of quilt loader, disabling single mods that may interfere and I've wasted so much time researching how individual things work to have it all stick together, but alas I failed and am now surrendering to asking to official support...

I use prismlauncher to play (to download the pack: new istance->modrinth->cabricality), but when I launch it with essential, it crashes with the report down below (which I cant understand and found little help searching it)

If it really is incompatible, then, I've also tried running the modpack on minehut (so I could still play with my friend), but I am not sure if it should even work or not on there since it supports forge, fabric, spongeforge, paper etc but not quilt (and it still doesnt work, but its probably my fault because I dont really know how to run the server modpack properly and found no guide on doing this for a host providing service such as minehut)
In the case minehut doesnt support it, what way of playing this modpack with my friend would I have available?

### What Should Happen?

the game cannot open, crashes on startup (pre-launch?)

### Steps to Reproduce

try to play the game with the "essential" mod installed with the cabricality modpack

### Cabricality Version Check

Yes, I'm playing with Cabricality 0.3.1

### Crash Log

https://paste.ubuntu.com/p/vTxzSrRR5K/

### Anything Else?

im very sad right now :(

**Comment by JieningYu** [comment]
Cabricality officially is incompatible with, and will never support `ESSENTIAL` cause we don't think it's great enough to be compatible with.

If you want to play with others, use a fast reserve proxy or use the `mcwifipnp` mod to play it online, which is compatible with this modpack.

BTW, currently the pack is no longer under maintenance.

**Comment by JieningYu** [comment]
The incompatible of mod `ESSENTIAL` is hard-coded in the `cabricality` mod, but the crash is not caused by the mod.

**Comment by KrLite** [comment]
> Cabricality officially is incompatible with, and will never support `ESSENTIAL` cause we don't think it's great enough to be compatible with.
> 
> If you want to play with others, use a fast reserve proxy or use the `mcwifipnp` mod to play it online, which is compatible with this modpack.
> 
> BTW, currently the pack is no longer under maintenance.

I will maintain this pack, but not for now. The pack is anyway not abandoned.

**Comment by JieningYu** [comment]
> > Cabricality officially is incompatible with, and will never support `ESSENTIAL` cause we don't think it's great enough to be compatible with.
> 
> > 
> 
> > If you want to play with others, use a fast reserve proxy or use the `mcwifipnp` mod to play it online, which is compatible with this modpack.
> 
> > 
> 
> > BTW, currently the pack is no longer under maintenance.
> 
> 
> 
> I will maintain this pack, but not for now. The pack is anyway not abandoned.

NOW it's not under maintenance

**Comment by KrLite** [comment]
> > > Cabricality officially is incompatible with, and will never support `ESSENTIAL` cause we don't think it's great enough to be compatible with.
> > 
> > 
> > > 
> > 
> > 
> > > If you want to play with others, use a fast reserve proxy or use the `mcwifipnp` mod to play it online, which is compatible with this modpack.
> > 
> > 
> > > 
> > 
> > 
> > > BTW, currently the pack is no longer under maintenance.
> > 
> > 
> > I will maintain this pack, but not for now. The pack is anyway not abandoned.
> 
> NOW it's not under maintenance

I agree, but you said ‘no longer’ 😭

**Comment by JieningYu** [comment]
Ai Ai
