### ISSUE TITLE
[BUG]: Extractor Machine not working

### ISSUE THREAD

**Issue by GuilhermeOT** [DM-Earth/Cabricality#179]
### What Happened?

I can't find a way to make the extractor machine to work, I've seen many tutorials and tried a lot of things but nothing seems to make the machine work.

### What Should Happen?

UI should pop up when I interact with the machine

### Steps to Reproduce

1.Place extractor machine by tree 2.Interact with it 3.Won't work

### Cabricality Version Check

Yes, I'm playing with Cabricality 0.3.1

**Comment by JieningYu** [comment]
The extractor machine does not have a UI. To use it, pipe out the fluid produced by it. (e.g. Fluid Pipes)
