### ISSUE TITLE
[Suggestion] Use Ad Astra as a replacement of Moon and Space Dimensions

### ISSUE THREAD

**Issue by Flamarine** [DM-Earth/Cabricality#18]
Ad Astra is currently more polished than Moon and Space Dimensions. Also it's open-soure so bug tracking is much easier.

**Comment by JieningYu** [comment]
I mentioned that removing Moon and Space Dimensions will break saves. The current solution is to keep M&S and add Ad Astra(though almost all items were banned from M&S)

**Comment by JieningYu** [comment]
Wait it won't break saves now. pog

**Comment by JieningYu** [comment]
<img width="250" alt="image" src="https://user-images.githubusercontent.com/61787533/184521416-a4a1326b-57d8-45a4-963e-dfcc462db5f0.png">
so it's a fabric version of beyond earth. inter
