### ISSUE TITLE
[BUG]: Essentials Mod not compatiable 

### ISSUE THREAD

**Issue by Hoosps** [DM-Earth/Cabricality#180]
### What Happened?

After adding the essentials mod to my pack, i get a "Internal Error" and it crashes

### Steps to Reproduce

1. Add Essentials to the Packs mod folder
2. launch pack
3. get crash menu

### Cabricality Version Check

Yes, I'm playing with Cabricality 0.3.1

### Crash Log

https://pastebin.com/k15RurBM

**Comment by JieningYu** [comment]
Duplicate of https://github.com/DM-Earth/Cabricality/issues/178
