### ISSUE TITLE
[MOD] Replace Malum with a New Mod

### ISSUE THREAD

**Issue by Gebardensprache** [DM-Earth/Cabricality#183]
### Mod Link

None

### Propose Reason?

`Mulum Quilt` has been archived and it is licensed on ARR.
In fact, we have to create a new mod to replace that.

Assignees:
- @Oganesson897 
- @RawDiamond
- @TexBlock 
- @KrLite

**Comment by TexBlock** [comment]
We don't necessarily need malum, I think we can use other mods to replace it.

And redeveloping a mod may result in a long development cycle.

**Comment by JieningYu** [comment]
use GitHub integrated features

**Comment by JieningYu** [comment]
Malum is officially releasing both Fabric and Forge versions

**Comment by RawDiamondMC** [comment]
> ### Mod Link
> 
> None
> ### Propose Reason?
> 
> `Mulum Quilt` has been archived and it is licensed on ARR. In fact, we have to create a new mod to replace that.
> 
> Assignees:
> 
>     * @Oganesson897
> 
>     * @rawdiamond
> 
>     * @TexBlock
> 
>     * @KrLite

I just notice this issue

You @ the wrong person

**Comment by JieningYu** [comment]
wlg

**Comment by IcedDog** [comment]
why dont assign me😡

**Comment by JieningYu** [comment]
![image](https://github.com/user-attachments/assets/93cb0969-4939-4067-bf0a-9bc88397f0f5)
