### ISSUE TITLE
Fluid Texture Issue

### ISSUE THREAD

**Issue by IcedDog** [DM-Earth/Cabricality#19]
I don't know if this is a KubeJS issue or not, but fluid (powered water and resin) gets untextured as long as it's flowing. I tried restarting the game a couple of times but problem still exists.
Log has no info or errors.
![N791BEK0$K(L4P$7CMVB V](https://user-images.githubusercontent.com/34804287/184593070-189d9ea2-b456-4dc2-8349-de8f754de86f.png)

**Comment by JieningYu** [comment]
It is a KubeJS issue.

**Comment by KrLite** [comment]
Check it here
KubeJS-Mods/KubeJS/issues/444
