### ISSUE TITLE
Infernal Mechanism crafting doesn't display right in REI

### ISSUE THREAD

**Issue by NyakoFox** [DM-Earth/Cabricality#25]
![image](https://user-images.githubusercontent.com/87289390/185762619-bd0a561e-062d-4e90-80e9-7f9474daa4e9.png)

**Comment by JieningYu** [comment]
REI x Create bug

**Comment by Derpford** [comment]
For future reference, what's the actual recipe? The quest line mentions 24(!) buckets of lava.

**Comment by JieningYu** [comment]
> For future reference, what's the actual recipe? The quest line mentions 24(!) buckets of lava.

https://github.com/DM-Earth/Cabricality/wiki
