### ISSUE TITLE
Crash when completing chapters/bounds in FTB quests

### ISSUE THREAD

**Issue by JieningYu** [DM-Earth/Cabricality#3]
For example: Deploy..Deploy..Deploy..

**Comment by NyakoFox** [comment]
![image](https://user-images.githubusercontent.com/87289390/182482787-877d4eac-fda7-439f-aa40-f244338803f0.png)

This stat doesn't exist anymore, it was changed in 1.17. You'll want to change it to `play_time`, which is "Time played".

**Comment by JieningYu** [comment]
👀

**Comment by KrLite** [comment]
Pog.

**Comment by NyakoFox** [comment]
This is actually still an issue, because there's two places where `play_one_minute` still show up; once in `overview.snbt` (in chapter 5) and one in `stage_4.snbt` (I don't remember what this file is for)
