### ISSUE TITLE
Copper Ore blocks can be smelted for 8 Copper Ingots

### ISSUE THREAD

**Issue by OdieHerpaderp** [DM-Earth/Cabricality#60]
This appears to not be intentional, as it is the only material that allows for this

**Comment by JieningYu** [comment]
provide a screenshot?

**Comment by OdieHerpaderp** [comment]
![copper](https://user-images.githubusercontent.com/36902415/194770430-e601a101-36a9-4025-a945-026c10f859cc.png)
This applies to both the regular ore and the deepslate variant.

**Comment by JieningYu** [comment]
ok
