### ISSUE TITLE
Mod Recommendation: BLAST

### ISSUE THREAD

**Issue by Derpford** [DM-Earth/Cabricality#68]
https://www.curseforge.com/minecraft/mc-mods/blast

- Provides various mining explosives:
  - basic Iron Bombs
  - Fortune-enchanted Golden Bombs
  - Hard-block-piercing Diamond Bombs
  - Confetti Bombs for celebrations
  - Naval Bombs that can detonate underwater
  - Amethyst Bombs that explode into shards for combat purposes
  - Stripmining Explosives that can dig long tunnels rapidly

Implementation notes:
- Consider adding sequenced assembly recipes for various bomb types.
- Also consider replacing the iron in iron bombs with andesite alloy (please help i'm drowning in andesite)

**Comment by KrLite** [comment]
Sorry for noticing that Blast is using All Rights Reserved License, which we can't include in our pack. But thanks for the proposal!
