### ISSUE TITLE
Mod Recommendation: Wall-Jump

### ISSUE THREAD

**Issue by Derpford** [DM-Earth/Cabricality#69]
https://www.curseforge.com/minecraft/mc-mods/wall-jump-unofficial-fabric

- Enables players to cling to walls by holding Sneak (default) while near a wall
- Holding a direction key while releasing Sneak jumps off of the wall in that direction
- Wall-jumps can be chained if you can jump between multiple walls
- Also includes a double-jump
- By default, prevents fall damage for smaller falls

This is just generally a fantastic movement/QoL mod. Navigating caves and factories is easier *and* way more fun with the climbing options this mod provides.

**Comment by KrLite** [comment]
That seems a good idea!
[Wall-Jump is added](https://github.com/DM-Earth/Cabricality/commit/7f7d5e53114e3914ae060da28ad089ea8646e87f) now.

**Comment by JieningYu** [comment]
will be considered in the future.

**Comment by KrLite** [comment]
This mod is just... Eerie. You can even fly.

This is too cheating and I think we can't add it.
