### ISSUE TITLE
Mod Recommendation: Catwalks, Inc.

### ISSUE THREAD

**Issue by Derpford** [DM-Earth/Cabricality#70]
https://www.curseforge.com/minecraft/mc-mods/catwalks-inc

- Adds craftable catwalks, ladders, and caged ladders
- Also includes a valve-handle-like lever alternative with analog output
- Catwalks can be painted in any dye color

With *Create Deco* still not updated, I'm really missing the catwalks. This mod provides.

Note: I suggest reworking the recipes to use Andesite Alloy here, too. There really is a shortage of good building blocks that use Andesite Alloy with Create Deco stuck on an older Create version.

**Comment by Derpford** [comment]
Alternatively, having a good non-bronze use for Tin would be fantastic.

**Comment by Derpford** [comment]
Aside: I just realized that Platforms from *Hephaestus*/*Tinker's Construct* can be *sort of* catwalk-like, but are somewhat awkward to use compared to Catwalks, Inc.'s catwalks.

**Comment by KrLite** [comment]
Wow. Interesting mod. [Now added.](https://github.com/DM-Earth/Cabricality/commit/f76f4411978abde3813ac7352333ed23b0c8a5f1)
