### ISSUE TITLE
Mod Recommendation: 'Dustrial Decor

### ISSUE THREAD

**Issue by Derpford** [DM-Earth/Cabricality#71]
https://www.curseforge.com/minecraft/mc-mods/dustrial-decor

- Lots of reasonably-priced decorative metal blocks.
- Padded blocks, which make for a good alternative to quartz as a "clean room" block
- Alternate door types
- Cardboard-based objects (note: may want to disable the "Cardboard Box" block to avoid confusion)
- Barbed iron bars and barbed chain link fences, for passive defense

Note: Since steel can be produced by Bulk Blasting, I'm going to recommend adding a Bulk *Smoking* recipe for Cast Iron Billets (should produce 4 per iron ingot), with another Smoking or Blasting recipe to convert Cast Iron into Industrial Iron (at a 2->1 ratio). The recipes *will* need tweaking even if we don't go that route; the existing recipes require *explicitly* coal, which is less than ideal for several reasons, so at minimum I'd want to change the recipe to allow using charcoal as well.

**Comment by JieningYu** [comment]
will use https://github.com/DM-Fabric-Ports/XKDeco-Quilt.
