### ISSUE TITLE
Alternate sources for farming Green Dye

### ISSUE THREAD

**Issue by Derpford** [DM-Earth/Cabricality#74]
I've traveled thousands of blocks in various directions from my base, and while I've found a lot of Terrestria's Outback biome, I haven't found any cactus.

Possible options:
1. Add a one-time purchase for Cactus. This would likely gate cactus behind the brass age, as that's the only way to get ahold of coins right now.
2. Add some alternative processing recipes for green dye which use more easily farmed resources. For instance, milling Cabbage could produce green dye.
3. Add a slime "culturing" recipe that produces slightly more than 1 slmeball from an input of slimeballs and other materials--perhaps a Mixer recipe using slime, sugar, and water? (This would overlap with the slimeball+water -> 1/2 slimeball+water recipe, which isn't necessarily a bad thing--it could invite new automation challenges to avoid wasting slimeballs!)

**Comment by EvanHsieh0415** [comment]
~~you need Nature's Compass~~

**Comment by EvanHsieh0415** [comment]
> 1. Add a one-time purchase for Cactus. This would likely gate cactus behind the brass age, as that's the only way to get ahold of coins right now.

Agree

> 2. Add some alternative processing recipes for green dye which use more easily farmed resources. For instance, milling Cabbage could produce green dye.

No comment

> 3. Add a slime "culturing" recipe that produces slightly more than 1 slmeball from an input of slimeballs and other materials--perhaps a Mixer recipe using slime, sugar, and water? (This would overlap with the slimeball+water -> 1/2 slimeball+water recipe, which isn't necessarily a bad thing--it could invite new automation challenges to avoid wasting slimeballs!)

Create has the recipe for slime ball

**Comment by JieningYu** [comment]
true.

**Comment by Derpford** [comment]
Create already has a slimeball recipe, yes. That's why I'm asking about
easier cactus access.

IMO, a lategame slime recipe that doesn't require green dye but *does*
require more complex automation would be an interesting solution to this.
Technically, cactus green can be acquired by shearing and grinding ferns,
but this isn't suitable for mass production.

**Comment by IcedDog** [comment]
shipment will be added in the next update

**Comment by IcedDog** [comment]
cactus is added to shipments

**Comment by IcedDog** [comment]
ok who deleted it
