### ISSUE TITLE
Issue with labels in the main menu

### ISSUE THREAD

**Issue by Rivgad** [DM-Earth/Cabricality#75]
All menu items are **"FTB Teams, FTB Quests, Quests Additions, FTB Library needs to be installed for Cabricality"**
![image](https://user-images.githubusercontent.com/55663166/198304124-5dda205b-d88c-4eb3-b943-778ecdd8efe0.png)

![image](https://user-images.githubusercontent.com/55663166/198303622-aa821e70-f4b5-4d52-8261-f10301d8159b.png)

**Comment by JieningYu** [comment]
Working as intended
