### ISSUE TITLE
[Bug] Necrotic bone can't be crafted

### ISSUE THREAD

**Issue by IcedDog** [DM-Earth/Cabricality#76]
https://discord.com/channels/999146491987902484/999146492973547572/1033826622769471558

**Comment by IcedDog** [comment]
wait is this fixed?

**Comment by JieningYu** [comment]
i dont know

**Comment by KrLite** [comment]
This has been fixed.
<img width="966" alt="image" src="https://user-images.githubusercontent.com/68179735/215084408-9928bcec-dae8-41e2-a428-3b195d3fac51.png">
