### ISSUE TITLE
较新版本的rei会在查看合成表时崩溃

### ISSUE THREAD

**Issue by ZZZank** [DM-Earth/Cabricality#77]
我使用的cab版本是fix kubejs error对应的自动构建，其中的rei在查看合成表时会崩溃。
崩溃会发生在切换合成表顶端的标签时，提示IndexOutOfBoundsException
旧版本（8.3.543）或者jei没有这个问题，最新版的rei(8.3.563)仍然存在这个问题
[crash-2022-10-30_22.05.15-client.txt](https://github.com/DM-Earth/Cabricality/files/9925305/crash-2022-10-30_22.05.15-client.txt)
[crash-2022-10-31_23.21.04-client.txt](https://github.com/DM-Earth/Cabricality/files/9925306/crash-2022-10-31_23.21.04-client.txt)

**Comment by JieningYu** [comment]
是否是rei自身问题？

**Comment by ZZZank** [comment]
> 是否是rei自身问题？

我改用jei时，没有发生过这个问题。旧版rei在cab0.1dev15与我用的这个自动构建版本也都没有问题，所以基本可以断定是新版rei的问题。
(以及，崩溃日志里提到的exception发生位置都指向了rei)

所以，（issue里忘说了）其实我建议降低rei的版本

**Comment by JieningYu** [comment]
can't reproduce
