### ISSUE TITLE
在 README 中说明 FTB Quests 、 FTB Teams 、 FTB Library 、 Quests Additions 应安装的版本

### ISSUE THREAD

**Issue by TexBlock** [DM-Earth/Cabricality#79]
如果不在 README 中说明 FTB Quests 、 FTB Teams 、 FTB Library 、 Quests Additions 应安装的版本，安装这些模组最新版本会遇到模组依赖问题。

**Comment by JieningYu** [comment]
https://github.com/FTBTeam/FTB-Quests/pull/655
