### ISSUE TITLE
Unreadable error message

### ISSUE THREAD

**Issue by EntityinArray** [DM-Earth/Cabricality#82]
![image](https://user-images.githubusercontent.com/18554021/201173763-6ab829e2-6863-4883-b84d-5345a4882fdc.png)
Error message is unreadable, this text replaces all button labels.
Please make a proper error message screen

Downloaded modpack from Modrinth, Cabricality 0.1-alpha-patch1

**Comment by JieningYu** [comment]
fixed in alpha2 using error notifier by shedaniel.
and this is readable: "FTB Teams, FTB Quests, Quests Additions, FTB Library mod needs to be installed for Cabricality"
