### ISSUE TITLE
Mod recommendation: Terra, for a more reasonable terrain

### ISSUE THREAD

**Issue by ZZZank** [DM-Earth/Cabricality#85]
1.18 的原版地形太破碎了，对摆放机器与修建建筑都不利。Terra的地形要好一点。
The original terrain of 1.18 is too broken, which is bad for placing machines and buildings. Terra's terrain is a little bit better.

**Comment by KrLite** [comment]
Agree, [and we now own it.](https://github.com/DM-Earth/Cabricality/commit/4269c8e1eb58f16cd1e3bcc95049780840ed9df2)

**Comment by KrLite** [comment]
well, because of the lack of tests, we now removed terra which is still in beta.
thanks for the suggestion though! we shall add it again after we have tested it.
