### ISSUE TITLE
The Market has broken quests

### ISSUE THREAD

**Issue by NyakoFox** [DM-Earth/Cabricality#9]
I'm playing this in survival so I haven't tested everything yet, but:

- [x] The Enderpack quest gives you two shulker shells and one chest. I'd imagine this is to craft a shulker box, and the quest description seems to talk about an ender backpack, however when I redeemed the quest, I quickly realized that the shulker box crafting recipe is disabled, and the only "useful" thing I could do with the shells was make an item vault from Create... except I could also just use lead sheets for that, making it useless as well. Was this quest supposed to give something different?

- [x] #11

- [x] The Fortress Locator gives an item which doesn't actually exist...

Also, every quest can only be used once, which I find a bit odd but I assume Create: Above and Beyond does the same thing.

**Comment by JieningYu** [comment]
the shulker box recipe is certainly a bug

**Comment by KrLite** [comment]
The Market has just simply migrated from CAB with no fixes and tests so unexpected things happen.
We will certainly fix these in the next patch, thanks for reporting.

**Comment by JieningYu** [comment]
And yep every quest can only be used once except gold coin <-> silver coin

**Comment by JieningYu** [comment]
same as cab

**Comment by JieningYu** [comment]
the patience barrels will have broken loot tables if it use the original cab loot tables.

**Comment by JieningYu** [comment]
all fixed except the barrels
