### ISSUE TITLE
terrain problem

### ISSUE THREAD

**Issue by ZZZank** [DM-Earth/Cabricality#95]
部分不同高低的地形之间的分界线太过笔直，同时也有许多浮空的方块，导致默认的地形看上去非常奇怪。
这是不是1.18原版的问题？有没有什么修复的方法？
Some dividing lines between terrains of different heights are too straight, and there are also many floating blocks, which makes the default terrain look very, very strange.
Is this 1.18 vanilla's problem? Is there any way to fix it?
<img width="652" alt="屏幕截图_20230111_200650" src="https://user-images.githubusercontent.com/47418975/211804226-f7513236-f75d-475f-b371-871063288da3.png">
![2023-01-11_19 56 45](https://user-images.githubusercontent.com/47418975/211804478-16bba439-11f2-42a7-8b4d-7d9d6fbb870c.png)

**Comment by JieningYu** [comment]
不知道

**Comment by KrLite** [comment]
Has little impact on game, will be considered in future.
