### ISSUE TITLE
[Bug] Strange furnace behaviour

### ISSUE THREAD

**Issue by ZZZank** [DM-Earth/Cabricality#96]
使用熔炉烧炼粉碎矿石时，如果输出槽是空的，产物就是三个粒，但如果输出槽已经有东西，产物就只有一个粒。
连续烧炼与间隔烧炼的结果是一样的，产物数量取决于输出槽是不是空。
When using a furnace to burn crushed ore, if the output slot is empty, the products are three nuggets, but if there is something in the output slot, the product will be only one nugget.
The results of continuous firing and interval firing are the same, and the quantity of products depends on whether the output slot is empty or not.
![default](https://user-images.githubusercontent.com/47418975/212082419-6d833558-06cc-4da1-8f2c-329ce5e61474.png)

**Comment by JieningYu** [comment]
This may be a vanilla bug

**Comment by KrLite** [comment]
Vanilla does not support smelting results that have more than 1 item. We used brrp to generate recipes, so might be a brrp bug.

**Comment by KrLite** [comment]
> Vanilla does not support smelting results that have more than 1 item. We used brrp to generate recipes, so might be a brrp bug.

No not a brrp bug, it does not handle this, we registrate these by recipe handler

**Comment by KrLite** [comment]
I suspect this is a quilt RecipeHandler problem

**Comment by JieningYu** [comment]
> I suspect this is a quilt RecipeHandler problem

Not. I think this is just a Vanilla issue

**Comment by JieningYu** [comment]
Vanilla DOES support multi-item output in recipes (because they're ItemStacks) but it dosen't support parsing multi-item output from json.

**Comment by JieningYu** [comment]
Vanilla defaults every smelting recipe's output is just 1 item. based
