### ISSUE TITLE
[Bug] 1 nugget per ore instead of 3

### ISSUE THREAD

**Issue by cilcoOf** [DM-Earth/Cabricality#97]
should be 3 nuggets per ore when melting, not 1

**Comment by JieningYu** [comment]
what do you mean

**Comment by cilcoOf** [comment]
Basically, what i mean is described in issue #96, when smelting crushed ore
in furnace, the output is 1 nugget instead of 3.

**Comment by cilcoOf** [comment]
Basically, what i mean is described in issue #96, when smelting crushed
ore in furnace, the output is 1 nugget instead of 3.

**Comment by JieningYu** [comment]
then this is duped
