### ISSUE TITLE
[Bug] Client crashes when looking up create:wrench's mechanical crafting recipe

### ISSUE THREAD

**Issue by KrLite** [DM-Earth/Cabricality#99]
As the title says.

[Download crash log](https://github.com/DM-Earth/Cabricality/files/10420286/latest.log) or [check it online.](https://paste.ubuntu.com/p/z5JhRs5gx2/)

**Comment by JieningYu** [comment]
Maybe this should be reported to Create Fabric.

**Comment by KrLite** [comment]
I don't know if this is a create's bug or cabf's bug because we have literally changed a lot on rei and recipes.

**Comment by KrLite** [comment]
Need to test to figure out what caused this

**Comment by KrLite** [comment]
So for now, I see it as a cabf bug.

**Comment by KrLite** [comment]
It is not a Create's bug.

<img width="966" alt="image" src="https://user-images.githubusercontent.com/68179735/215257668-52770757-a6cf-4121-8b45-7d75ddb68aef.png">

**Comment by KrLite** [comment]
Well, I don't know when this bug disappears, but it does, so not crashing now

<img width="966" alt="image" src="https://user-images.githubusercontent.com/68179735/215257743-d11f995c-9794-4941-a8ca-35ab0ea7791b.png">
